name: CrystalKills
main: com.crystalcraftmc.crystalkills.CrystalKills
version: ${version}
description: Show players how many kills they have.
authors: [jflory7, jwood9198, Jacc734]

commands:
 crystalkills:
  description: Shows a player how many players they killed.
   aliases: [ck, ccmckills, kills]
